/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "img/hero.png",
        "heroText": "logo",
        "tagline": "博客",
        "actionText": null,
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "个人笔记博客",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。",
            "footer": "MIT Licensed | Copyright © 2018-present Evan You"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-66a4fdcb",
      "path": "/"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/hero.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "External",
        "link": "https://google.com",
        "target": "_self",
        "rel": ""
      },
      {
        "text": "Guide",
        "link": "/guide/",
        "target": "_blank"
      },
      {
        "text": "Languages",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      }
    ],
    "sidebar": [
      {
        "title": "Group 1",
        "path": "/foo/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/"
        ]
      },
      {
        "title": "Group 2",
        "children": [],
        "initialOpenGroupIndex": -1
      }
    ]
  }
}